SET(WEBRTC_SRC_LIST
  ${WEBRTC_SRC_LIST}
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audio_coding.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audiodecode.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audiodecode.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audiodecodeG711A.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audiodecodeG711A.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audiodecodeG711U.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audiodecodeG711U.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audiodecodeG722.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audiodecodeG722.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audioencode.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audioencode.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audioencodeG711A.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audioencodeG711A.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audioencodeG711U.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audioencodeG711U.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audioencodeG722.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/audioencodeG722.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g711.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g711.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g711_interface.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g711_interface.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g722_decode.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g722_enc_dec.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g722_encode.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g722_interface.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/g722_interface.h
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/arith_routines.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/arith_routines_hist.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/arith_routines_logist.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/encode_lpc_swb.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/entropy_coding.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/filter_functions.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/filterbanks.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/filterbank_tables.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/intialize.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/lpc_analysis.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/lpc_gain_swb_tables.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/lpc_shape_swb12_tables.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/lpc_shape_swb16_tables.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/lpc_tables.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/pitch_estimator.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/pitch_filter.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/pitch_gain_tables.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/pitch_lag_tables.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/spectrum_ar_model_tables.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/audio_decoder.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/audio_encoder.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/audio_decoder_isac.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/audio_encoder_isac.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/bandwidth_estimator.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/crc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/decode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/decode_bwe.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/encode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/fft.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/isac.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/lattice.c
  ${CMAKE_CURRENT_SOURCE_DIR}/webrtc/modules/audio_coding/codecs/isac/main/source/transform.c
)